### ISSUE TITLE
Add Terms and Condition Page or Text

### ISSUE THREAD

**Issue by sagarkaurav** [herdhq/covid-front-end#3]
Add TnC page to make sure herdhq is not liable for the information shown on the portal

**Comment by 53R3N1TY** [comment]
Can you point us in the right direction from where we can get this kinda text because it will take so much time if we start writing the content now?

**Comment by sagarkaurav** [comment]
https://policymaker.io/terms-and-conditions/ looks good. Maybe disclaimer is more than enough

**Comment by sagarkaurav** [comment]
Disclaimer example: https://armsp.github.io/covid19.in/

**Comment by secxena** [comment]
@sagarkaurav can you create a pull request with a disclaimer in the footer ?

**Comment by secxena** [comment]
Hi, @sagarkaurav this is done. live on production.
